name: azure-devops-extension-workshop

on:
  push:
    branches: 
      - master
      - develop
      # match an pushes on feature/* and feature/<any sub branch>/*
      - 'feature/**'
    # don't run when changes made to these folders 
    paths-ignore:
      - '.vscode/**'
      - 'demo-images/**'
      - README.md

jobs:
  test:
    name: test
    runs-on: windows-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
        
      - name: Install dependencies
        run: |
          make ni
          npm install -g tfx-cli


      - name: Create vsix file
        run: |
          mkdir src/artifact/
          cd src/artifact/ && npx tfx-cli extension create

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: azure-devops-extension-artifact
          path: ${{github.workspace}}/src/artifact/
      
      - name: publish to marketplace
        if: github.ref == 'refs/heads/master'
        run: npm run deploy ${{ env.PAT }}

      - name: create a release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          release_name: v${{ steps.gitversion.outputs.semVer }}
