name: azure-devops-extension-workshop

on:
  push:
    branches: 
      - master
      - develop
      # match an pushes on feature/* and feature/<any sub branch>/*
      - 'feature/**'
    # don't run when changes made to these folders 
    paths-ignore:
      - '.vscode/**'
      - 'demo-images/**'
      - README.md

  pull_request:
    branches: 
      - master
      - develop
      # match an pushes on feature/* and feature/<any sub branch>/*
      - 'feature/**'

jobs:
  test:
    name: Execute Tests
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [10, 12, 14]
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: cd src && npm install

      - name: Execute unit tests
        run: make t

  package:
    name: Package Extension
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          cd src && npm install
          npm install -g tfx-cli

      - name: Create vsix file
        run: |
          mkdir src/artifact/
          cd src && npm run package

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: azure-devops-extension-artifact
          path: ${{github.workspace}}/src/artifact/

  publish:
    name: Publish Extension
    needs: [ test, package ]
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          cd src && npm install
          npm install -g tfx-cli
      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      
      - name: publish to marketplace
        if: github.ref == 'refs/heads/master'
        run: npm run deploy ${{ env.PAT }}

      - name: create a release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ steps.gitversion.outputs.semVer }}
          release_name: v${{ steps.gitversion.outputs.semVer }}
