name: azure-devops-extension-workshop

on:
  push:
    branches: 
      - master
      - develop
      # match an pushes on feature/* and feature/<any sub branch>/*
      - 'feature/**'
    # don't run when changes made to these folders 
    paths-ignore:
      - '.vscode/**'
      - 'demo-images/**'
      - README.md

  pull_request:
    branches: 
      - master
      - develop
      # match an pushes on feature/* and feature/<any sub branch>/*
      - 'feature/**'

jobs:
  test:
    name: Execute Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        node: [10, 12, 14]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: make ni

      - name: Execute unit tests
        run: make t

  package:
    name: Package Extension
    needs: test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          make ni
          npm install -g tfx-cli

      - name: Remove test scripts
        run: rm -fv ${{github.workspace}}/**/*.spec.ts

      - name: Build project
        run: cd src && npm run package
      
      - name: Remove typescript files
        run: rm -fv ${{github.workspace}}/**/*.ts

      - name: Upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: azure-devops-extension-artifact
          path: ${{github.workspace}}/src/out/

  publish:
    name: Publish Extension
    needs: [ test, package ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          make ni
          npm install -g tfx-cli

      - name: Download extension artifact
        uses: actions/download-artifact@v2
        id: download
        with:
          name: azure-devops-extension-artifact
          path: ~/download/artifact

      - name: Publish to marketplace
        if: github.ref == 'refs/heads/master'
        run: cd src && npm run publish --auth-type 'pat' --token ${{ secrets.AZURE_DEVOPS_PAT_TOKEN }} --share-with TCSTechCommWorkshop

      - name: Create a release
        if: github.ref == 'refs/heads/master'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
